config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :quarters do
    resources :sprints
    resources :initiatives
  end

  resources :teams
  resources :planitems

  get 'plan', to: redirect("/quarters"), as: :plan_redirect
  get 'plan/:id', to: 'plan#index', as: :plan

  root to: 'quarters#index'
end

app/models/quarter.rb
class Quarter < ActiveRecord::Base
	validates :name, :presence => true
	has_many :sprints, -> { order(:name) }, :dependent => :destroy
	has_many :initiatives, -> { order("priority asc, name asc") }, :dependent => :destroy
end

app/controllers/quarters_controller.rb
class QuartersController < ApplicationController
  # GET /quarters
  # GET /quarters.json
  def index
    @quarters = Quarter.order(:name)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @quarters }
    end
  end

  # GET /quarters/1
  # GET /quarters/1.json
  def show
    @quarter = Quarter.find(params[:id])
	@initiative = @quarter.initiatives.new
	@sprint = @quarter.sprints.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @quarter }
    end
  end

  # GET /quarters/new
  # GET /quarters/new.json
  def new
    @quarter = Quarter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @quarter }
    end
  end

  # GET /quarters/1/edit
  def edit
    @quarter = Quarter.find(params[:id])
  end

  # POST /quarters
  # POST /quarters.json
  def create
    @quarter = Quarter.new(quarter_params)

    respond_to do |format|
      if @quarter.save
        format.html { redirect_to @quarter, notice: 'Quarter was successfully created.' }
        format.json { render json: @quarter, status: :created, location: @quarter }
      else
        format.html { render action: "new" }
        format.json { render json: @quarter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /quarters/1
  # PUT /quarters/1.json
  def update
    @quarter = Quarter.find(params[:id])

    respond_to do |format|
      if @quarter.update_attributes(quarter_params)
        format.html { redirect_to @quarter, notice: 'Quarter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @quarter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quarters/1
  # DELETE /quarters/1.json
  def destroy
    @quarter = Quarter.find(params[:id])
    @quarter.destroy

    respond_to do |format|
      format.html { redirect_to quarters_url }
      format.json { head :no_content }
    end
  end

  private
  def quarter_params
    params.require(:quarter).permit(:name, :grouping)
  end
end

app/helpers/quarters_helper.rb
module QuartersHelper
end

app/views/quarters/_form.html.erb
<%= form_for(@quarter) do |f| %>
  <% if @quarter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quarter.errors.count, "error") %> prohibited this quarter from being saved:</h2>

      <ul>
      <% @quarter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit "Submit", :class => "button" %>
  </div>
<% end %>

app/views/quarters/edit.html.erb
<h1>Editing quarter</h1>

<%= render 'form' %>

<%= link_to 'back', @quarter %>

app/views/quarters/index.html.erb
<h1>Quarters</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Actions</th>
  </tr>

<% @quarters.each do |quarter| %>
  <tr>
    <td><%= link_to quarter.name, plan_path(:id => quarter.name) %></td>
    <td>
		<% if is_super_admin?(current_user.login) -%>
		<%= link_to "Manage", quarter %>
		<% end %>
	</td>
  </tr>
<% end %>
</table>

<br />

<% if is_super_admin?(current_user.login) -%>
<%= link_to 'New Quarter', new_quarter_path, :class => "button" %>
<% end %>

app/views/quarters/new.html.erb
<h1>New quarter</h1>

<%= render 'form' %>

<%= link_to 'back', quarters_path %>

app/views/quarters/show.html.erb
<h1>Quarter: <%= @quarter.name %></h1>

<div style="margin-bottom: 10px">
<%= link_to 'back', quarters_path %>
<% if is_super_admin?(current_user.login) -%>
 | <%= link_to 'edit', edit_quarter_path(@quarter) %> | <%= link_to 'delete', @quarter, confirm: "Are you sure you want to delete #{@quarter.name}?", method: :delete %>
<% end %>
</div>

<table style="width: 100%">
<tr>
<td valign="top">
	<h2>Initiatives</h2>
	<%= render @quarter.initiatives %>
	<h3>Add a New Initiative</h3>
	<%= render "initiatives/form" %>
</td>
<td valign="top">
	<h2>Sprints</h2>
	<%= render @quarter.sprints %>
	<h3>Add a New Sprint</h3>
	<%= render "sprints/form" %>
</td>
</tr>
</table>