config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :quarters do
    resources :sprints
    resources :initiatives
  end

  resources :teams
  resources :planitems

  get 'plan', to: redirect("/quarters"), as: :plan_redirect
  get 'plan/:id', to: 'plan#index', as: :plan

  root to: 'quarters#index'
end

app/models/initiative.rb
class Initiative < ActiveRecord::Base
	validates :name, :presence => true
	validates :priority, :numericality => { :greater_than_or_equal_to => 0, :only_integer => true }
 
	belongs_to :quarter
end

app/controllers/initiatives_controller.rb
class InitiativesController < ApplicationController
  # GET /initiatives
  # GET /initiatives.json
  def index
	@quarter = Quarter.find(params[:quarter_id])
	redirect_to quarter_path(@quarter)
  end

  # GET /initiatives/1
  # GET /initiatives/1.json
  def show
    @initiative = Initiative.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @initiative }
    end
  end

  # GET /quarters/1/initiatives/new
  # GET /quarters/1/initiatives/new.json
  def new
	@quarter = Quarter.find(params[:quarter_id])
    @initiative = @quarter.initiatives.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @quarter }
    end
  end

  # GET /quarter/1/initiatives/1/edit
  def edit
	@quarter = Quarter.find(params[:quarter_id])
    @initiative = @quarter.initiatives.find(params[:id])
  end

  # POST /initiatives
  # POST /initiatives.json
  def create
	@quarter = Quarter.find(params[:quarter_id])
	@initiative = @quarter.initiatives.create(initiative_params)

    respond_to do |format|
      if @initiative.save
        format.html { redirect_to quarter_path(@quarter), notice: "#{@initiative.name} was successfully created." }
        format.json { render json: @initiative, status: :created, location: @initiative }
      else
        format.html { render action: "new" }
        format.json { render json: @initiative.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /initiatives/1
  # PUT /initiatives/1.json
  def update
	@quarter = Quarter.find(params[:quarter_id])
    @initiative = @quarter.initiatives.find(params[:id])

    respond_to do |format|
      if @initiative.update_attributes(initiative_params)
        format.html { redirect_to @quarter, notice: 'Initiative was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @initiative.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /initiatives/1
  # DELETE /initiatives/1.json
  def destroy
	@quarter = Quarter.find(params[:quarter_id])
    @initiative = @quarter.initiatives.find(params[:id])
    @initiative.destroy

    respond_to do |format|
      format.html { redirect_to quarter_path(@quarter) }
      format.json { head :no_content }
    end
  end

  private
  def initiative_params
    params.require(:initiative).permit(:name, :priority)
  end
end

app/helpers/initiatives_helper.rb
module InitiativesHelper
end

app/views/initiatives/_form.html.erb
<%= form_for([@initiative.quarter, @initiative]) do |f| %>
  <% if @initiative.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@initiative.errors.count, "error") %> prohibited this initiative from being saved:</h2>

      <ul>
      <% @initiative.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :priority %>
    <%= f.number_field :priority, :min => 0 %>
  </div>
  <div class="actions">
    <%= f.submit "Submit", :class => "button" %>
  </div>
<% end %>

app/views/initiatives/_initiative.html.erb
<% if initiative.id != nil %>
<%= link_to "#{initiative.priority}. #{initiative.name}", edit_quarter_initiative_path(initiative.quarter, initiative) %><br/>
<% end %>

app/views/initiatives/edit.html.erb
<h1>Editing initiative</h1>

<%= render 'form' %>

<%= link_to 'back', quarter_path(@initiative.quarter) %>
<%= link_to 'delete', quarter_initiative_path(@initiative.quarter, @initiative), confirm: 'Are you sure you want to delete this initiative?', method: :delete %>

app/views/initiatives/index.html.erb
<h1>Listing initiatives</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Priority</th>
    <th>Quarter</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @initiatives.each do |initiative| %>
  <tr>
    <td><%= initiative.name %></td>
    <td><%= initiative.priority %></td>
    <td><%= initiative.quarter %></td>
    <td><%= link_to 'Show', initiative %></td>
    <td><%= link_to 'Edit', edit_initiative_path(initiative) %></td>
    <td><%= link_to 'Destroy', initiative, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Initiative', new_initiative_path %>

app/views/initiatives/new.html.erb
<h1>Adding Initiative for <%= @initiative.quarter.name %></h1>

<%= render 'form' %>

<%= link_to 'back', quarter_path(@initiative.quarter) %>

app/views/initiatives/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @initiative.name %>
</p>

<p>
  <b>Priority:</b>
  <%= @initiative.priority %>
</p>

<p>
  <b>Quarter:</b>
  <%= @initiative.quarter %>
</p>


<%= link_to 'Edit', edit_initiative_path(@initiative) %> |
<%= link_to 'Back', initiatives_path %>