config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :quarters do
    resources :sprints
    resources :initiatives
  end

  resources :teams
  resources :planitems

  get 'plan', to: redirect("/quarters"), as: :plan_redirect
  get 'plan/:id', to: 'plan#index', as: :plan

  root to: 'quarters#index'
end

app/models/sprint.rb
class Sprint < ActiveRecord::Base
	validates :name, :presence => true
	belongs_to :quarter
end

app/controllers/sprints_controller.rb
class SprintsController < ApplicationController
  # GET /sprints
  # GET /sprints.json
  def index
	@quarter = Quarter.find(params[:quarter_id])
	redirect_to quarter_path(@quarter)
  end

  # GET /sprints/1
  # GET /sprints/1.json
  def show
    @sprint = Sprint.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sprint }
    end
  end

  # GET /quarters/1/sprints/new
  # GET /quarters/1/sprints/new.json
  def new
	@quarter = Quarter.find(params[:quarter_id])
    @sprint = @quarter.sprints.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sprint }
    end
  end

  # GET /sprints/1/edit
  def edit
    @sprint = Sprint.find(params[:id])
  end

  # POST /sprints
  # POST /sprints.json
  def create
	@quarter = Quarter.find(params[:quarter_id])
    @sprint = @quarter.sprints.create(sprint_params)

    respond_to do |format|
      if @sprint.save
        format.html { redirect_to quarter_path(@quarter), notice: "#{@sprint.name} was successfully created." }
        format.json { render json: @sprint, status: :created, location: @sprint }
      else
        format.html { render action: "new" }
        format.json { render json: @sprint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sprints/1
  # PUT /sprints/1.json
  def update
	@quarter = Quarter.find(params[:quarter_id])
    @sprint = @quarter.sprints.find(params[:id])

    respond_to do |format|
      if @sprint.update_attributes(sprint_params)
        format.html { redirect_to @quarter, notice: 'Sprint was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sprint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sprints/1
  # DELETE /sprints/1.json
  def destroy
	@quarter = Quarter.find(params[:quarter_id])
    @sprint = @quarter.sprints.find(params[:id])
    @sprint.destroy

    respond_to do |format|
      format.html { redirect_to quarter_path(@quarter) }
      format.json { head :no_content }
    end
  end

  private
  def sprint_params
    params.require(:sprint).permit(:name)
  end
end

app/helpers/sprints_helper.rb
module SprintsHelper
end

app/views/sprints/_form.html.erb
<%= form_for([@sprint.quarter, @sprint]) do |f| %>
  <% if @sprint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sprint.errors.count, "error") %> prohibited this sprint from being saved:</h2>

      <ul>
      <% @sprint.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit "Submit", :class => "button" %>
  </div>
<% end %>

app/views/sprints/_sprint.html.erb
<% if sprint.id != nil %>
<%= link_to sprint.name, edit_quarter_sprint_path(sprint.quarter, sprint) %><br/>
<% end %>

app/views/sprints/edit.html.erb
<h1>Editing sprint</h1>

<%= render 'form' %>

<%= link_to 'back', quarter_path(@sprint.quarter) %>
<%= link_to 'delete', quarter_sprint_path(@sprint.quarter, @sprint), confirm: 'Are you sure you want to delete this sprint?', method: :delete %>

app/views/sprints/index.html.erb
<h1>Listing sprints</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Quarter</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sprints.each do |sprint| %>
  <tr>
    <td><%= sprint.name %></td>
    <td><%= sprint.quarter %></td>
    <td><%= link_to 'Show', sprint %></td>
    <td><%= link_to 'Edit', edit_sprint_path(sprint) %></td>
    <td><%= link_to 'Destroy', sprint, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sprint', new_sprint_path %>

app/views/sprints/new.html.erb
<h1>Adding Sprint for <%= @sprint.quarter.name %></h1>

<%= render 'form' %>

<%= link_to 'Back', quarter_path(@sprint.quarter) %>

app/views/sprints/show.html.erb
<p>
  <b>Name:</b>
  <%= @sprint.name %>
</p>

<p>
  <b>Quarter:</b>
  <%= @sprint.quarter %>
</p>


<%= link_to 'Edit', edit_sprint_path(@sprint) %> |
<%= link_to 'Back', sprints_path %>