config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :quarters do
    resources :sprints
    resources :initiatives
  end

  resources :teams
  resources :planitems

  get 'plan', to: redirect("/quarters"), as: :plan_redirect
  get 'plan/:id', to: 'plan#index', as: :plan

  root to: 'quarters#index'
end

app/controllers/plan_controller.rb
class PlanController < ApplicationController
  def noqtr
	redirect_to quarters_path
  end

  def index
    @teams = Team.where(:grouping => ["Applications", "Services"]).order("grouping", :name)
	@quarter = Quarter.where(:name => params[:id]).first

	@filters = []
	# start out with filters from the session if they exist
	@filters = session[:filter] if session.include?(:filter)

	# but, if we have params, override the session
	if params[:filter] != nil
		# merge in any new filters from the params
		@filter_params = params[:filter].map { |f| f.to_i }
		@filters = @filter_params
		# put the filters back in the session
		session[:filter] = @filters
	else
		@planitems = {}
	end

	# look up the plan items matching the filters
	planitems = Planitem.joins(:initiative).where(:initiative_id => @filters).order("initiatives.priority asc", :description)
	@planitems = planitems_to_hash planitems

	# map the initiatives to a 0-based index so that we can colorize
	@colormap = {}
	@quarter.initiatives.each_with_index do |initiative, index|
		@colormap[initiative.id] = index
	end

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  private
  def planitems_to_hash(planitems)
	hash = {}
	planitems.each do |i|
		# do we have the team in the hash?
		if !hash.include?(i.team_id)
			hash[i.team_id] = {}
		end
		team = hash[i.team_id]
		# do we have the sprint for this team?
		if !team.include?(i.sprint_id)
			team[i.sprint_id] = []
		end
		# do we have an array of sprints?
		sprints = team[i.sprint_id];
		sprints << i
	end
	hash
  end
end

app/views/plan/index.html.erb
<%= form_tag(plan_path, :method => "get", :id => 'filterform') do %>
	<% @quarter.initiatives.each do |initiative| %>
		<div style="float:left;padding:5px" class="initiative<%= @colormap[initiative.id] %>">
		<%= check_box_tag "filter[]", initiative.id, @filters.include?(initiative.id), :onchange => "document.getElementById('filterform').submit();" %>
		<%= label_tag "filter[#{initiative.name}]", initiative.name %>
		</div>
	<% end %>
	<div style="clear:both"></div>
<% end %>

<table style="width: 100%">
<tbody>
<% @teams.each_with_index do |team, index| %>
<% if index % 10 == 0 %>
<tr>
<th>Team (Grouping)</th>
<% @quarter.sprints.each do |sprint| %>
<th><%= sprint.name %></th>
<% end %>
</tr>
<tr>
<td>Legend</td>
<td colspan="<%= @quarter.sprints.length %>">
	<span class="sprintListItem" style="display: inline-block;"><span class="planItemType planItemTypeN"></span>Normal, not committed</span>
	<span class="sprintListItem" style="display: inline-block;"><span class="planItemType planItemTypeN">&#x2713;</span>Normal, committed</span>
	<span class="sprintListItem" style="display: inline-block;"><span class="planItemType planItemTypeD"></span>Dependency, not committed</span>
	<span class="sprintListItem" style="display: inline-block;"><span class="planItemType planItemTypeD">&#x2713;</span>Dependency, committed</span>
	<span class="sprintListItem" style="display: inline-block;"><span class="planItemType planItemTypeI"></span>Impact, not committed</span>
	<span class="sprintListItem" style="display: inline-block;"><span class="planItemType planItemTypeI">&#x2713;</span>Impact, committed</span>
</td>
</tr>
<% end %>

<tr class="<%= (index % 2 != 0) ? 'oddRow' : 'evenRow' %>">
<td><%= team.name %><br/>(<%= team.grouping %>)</td>
	<% @quarter.sprints.each do |sprint| %>
	<td valign="top">
		<%= link_to "+", new_planitem_path + "?team=#{team.id}&sprint=#{sprint.id}", :title => "Add a new item for #{team.name} in #{sprint.name}.", :class => "circleButton" %>
		<% 
			if @planitems.include?(team.id) && @planitems[team.id].include?(sprint.id)
				@planitems[team.id][sprint.id].each do |i|
					planItemTypeChar = i.itemtype != nil && i.itemtype.length > 0 ? i.itemtype[0].upcase : 'N'
					if i.itemtype == nil || i.itemtype == 'normal'
						iconMessage = "Normal item is %scommitted." % (!i.committed? ? "NOT " : "")
					else
						iconMessage = "%s is %scommitted." % [i.itemtype.capitalize, (!i.committed? ? "NOT " : "")]
					end
		%>
				<div class="sprintListItem initiative<%= @colormap[i.initiative.id] %>"><span title="<%= iconMessage %>" class="planItemType planItemType<%= planItemTypeChar %>"><%= i.committed? ? raw("&#x2713;") : "" %></span><%= link_to i.description, edit_planitem_path(i) %></div>
		<%
				end
			end %>
	</td>
	<% end %>
</tr>
<% end %>
</tbody>
</table>